---
- name: Load and commit ISIS Traceoptions configuration data on a device running Junos OS
  hosts: routers
  roles:
    - Juniper.junos
  connection: local
  gather_facts: no
  tasks:
    - name: Checking NETCONF connectivity
      wait_for:
        host: "{{ inventory_hostname }}"
        port: 830
        timeout: 5
    - name: Apply ISIS Traceoptions configuration and commit
      juniper_junos_config:
        user: "{{ username }}"
        password: "{{ password }}"
        load: "set"
        format: "text"
        comment: "Baseline ISIS traceoptions configuration - Ansible-configured"
        lines:
          - "set protocols isis traceoptions file isis size 10m files 10 world-readable"
          - "set protocols isis traceoptions flag error detail" 
          - "set protocols isis level 2 wide-metrics-only" 
          - "set protocols isis level 2 prefix-export-limit 4000" 
      register: response
    - name: Print the response
      debug:
        var: response
