---
- name: Load and commit ASN configuration data on a device running Junos OS
  hosts: routers
  roles:
    - Juniper.junos 
  connection: local
  gather_facts: no
  tasks: 
    - name: Checking NETCONF connectivity
      wait_for: 
        host: "{{ inventory_hostname }}" 
        port: 830  
        timeout: 5
    - name: Apply ASN configuration and commit
      juniper_junos_config: 
        user: "{{ username }}"
        password: "{{ password }}"
        load: "set"
        format: "text"
        comment: "Changing the router's AS number - Ansible-configured"
        lines:
          - "set routing-options autonomous-system 65000"
      register: response
    - name: Print the response
      debug:
        var: response
