---
- name: Load and commit BGP PTMU Discovery configuration data on a device running Junos OS
  hosts: routers
  roles:
    - Juniper.junos 
  connection: local
  gather_facts: no
  tasks: 
    - name: Checking NETCONF connectivity
      wait_for: 
        host: "{{ inventory_hostname }}" 
        port: 830  
        timeout: 5
    - name: Apply BGP PTMUd configuration and commit
      juniper_junos_config: 
        #mode: "None" 
        user: "{{ username }}"
        password: "{{ password }}"
        load: "set"
        format: "text"
        comment: "Enabling TCP PMTU for BGP - Ansible-configured"
        lines:
          - "set protocols bgp mtu-discovery"
      register: response
    - name: Print the response
      debug:
        var: response
