---
- name: Load and commit Default Route configuration data on a device running Junos OS
  hosts: routers
  roles:
    - Juniper.junos 
  connection: local
  gather_facts: no
  tasks: 
    - name: Checking NETCONF connectivity
      wait_for: 
        host: "{{ inventory_hostname }}" 
        port: 830  
        timeout: 5
    - name: Apply Default Route configuration and commit
      juniper_junos_config: 
        user: "{{ username }}"
        password: "{{ password }}"
        load: "set"
        format: "text"
        comment: "Configuring the default route characteristics - Ansible-configured"
        lines:
          - "set routing-options rib inet6.0 static route ::/0 retain"
          - "set routing-options rib inet6.0 static route ::/0 no-readvertise"
          - "set routing-options static route 0/0 retain"
          - "set routing-options static route 0/0 no-readvertise"
      register: response
    - name: Print the response
      debug:
        var: response
